version: '3'

services:
  metacubexd:
    container_name: metacubexd
    image: ghcr.geekery.cn/metacubex/metacubexd
    restart: always
    ports:
      - '17890:80'

  meta:
    container_name: meta
    image: hub.icert.top/metacubex/mihomo:Alpha
    restart: always
    pid: host
    ipc: host
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml
      - /dev/net/tun:/dev/net/tun